version: '3.3'


services:

  backend:
    build:
      context: ./hotel
      dockerfile: Dockerfile
    env_file:
    - ./.env
    volumes:
      - static:/backend/static/
      - media:/backend/media/


  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/var/html/media/
      - static:/var/html/static/
    depends_on:
      - backend

volumes:
  static:
  media: