version: '3.3'


services:

  backend:
    image: grandkol/anna_hotel_backend
    env_file:
    - .env
    volumes:
      - static:/backend_static



  nginx:
    image: grandkol/anna_hotel_gateway
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend

volumes:
  static: